# Generated by Django 3.2 on 2021-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0004_auto_20210508_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('headache', '두통'), ('stomachache', '복통'), ('abrasion', '찰과상'), ('dermatitis', '피부염'), ('etc', '기타')], default='etc', max_length=200),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
