# Generated by Django 3.2 on 2021-06-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0007_auto_20210619_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='android.medicine'),
        ),
    ]
