# Generated by Django 3.2 on 2021-06-21 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0008_alter_comment_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='android.medicine'),
        ),
    ]
