# Generated by Django 3.1.6 on 2021-06-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0010_auto_20210621_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
